baseURL = 'https://kikiraihan.github.io'
languageCode = 'en-us'
title = 'Moh Zulkifli Katili'
theme="researcher"

disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Moh Zulkifli Katili"
  description = "A Software Engineer. Love Programming, Data Science, and Graphic Design also."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  info = [
    "- Software Developer -",
  ]
  subinfo = [
    "Web-dev",
    "Machine Learning",
    "Knowledge Graph",
  ]
  avatarURL = "avatar_home4_enh.jpg"
  #gravatar = "mohzulkiflikatili@gmail.com"
  
  [params.footer]
    text = "Intellectual Power and Technical Prowess"
    #text = "Talk about Web, data, network science and Knowledge Graph"
    #url = "mailto:mohzulkiflikatili@gmail.com"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-facebook"
    title = "facebook"
    url = "https://www.facebook.com/astro.raihan/"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/inikikikatili"
  [[params.socialIcons]]
    icon = "fab fa-instagram"
    title = "Instagram"
    url = "https://www.instagram.com/inikikikatili/"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/kikiraihan"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/moh-zulkifli-katili-3ba18319a/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:mohzulkiflikatili@gmail.com"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4
  [[menu.main]]
    name = "Project"
    url = "/projects"
    weight = 2
  #[[menu.main]]
   # name = "Blogs"
    #url = "/blogs"
    #weight = 3
  
  

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files